server:
  port:
    3000


spring:
  config:
    import: optional:configserver:http://localhost:8000/
  cloud:
    config:
      uri: http://localhost:8000/
      name: userservice

  security:
    user:
      name: dev
      password: dev
      role: ADMIN

#exclude devtools props
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    url: jdbc:h2:mem:userserviceDB
    driverClassName: org.h2.Driver
    username: sa
    password:


  profile:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"





