spring:
  application:
    name: user-service
  profiles:
    active: dev


  config:
    import: optional:configserver:http://localhost:8000/
    config:
      uri: http://localhost:8000/
      name: userservice


  datasource:
    url: jdbc:h2:mem:userserviceDB
#    url: jdbc:h2:file:${user.home}/Desktop/DB
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true  #will be present at /h2-console

#  sleuth:
#    sampler:
#      probability: 1
#  zipkin:
##    discoveryClientEnabled: false
#    baseUrl: http://localhost:9411/


management:
  endpoints:
    web:
      exposure:
        include: "*"





